# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to='myapp.User')),
                ('faved_users', models.ManyToManyField(related_name='faved_travels', to='myapp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='joined_users',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
