# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181121_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='faved_users',
            field=models.ManyToManyField(related_name='faved_items', to='myapp.User'),
        ),
    ]
